const products=window.PRODUCTS||[],grid=document.querySelector("#productGrid"),tpl=document.querySelector("#productTemplate"),cart=new Map();let active=null;
const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v);
function art(p){const c=p.type==="mug"?"mug":p.type==="cap"?"cap":"shirt";return `<div class="product-object ${c}" style="background:${p.bg};color:${p.fg}">${p.art}</div>`}
function render(filter="all",query=""){grid.innerHTML="";products.filter(p=>(filter==="all"||p.category===filter)&&(`${p.name} ${p.sub} ${p.category}`.toLowerCase().includes(query.toLowerCase()))).forEach(p=>{const n=tpl.content.cloneNode(true);n.querySelector(".product-badge").textContent=p.badge;n.querySelector(".product-object-wrap").innerHTML=art(p);n.querySelector("h3").textContent=p.name;n.querySelector(".product-copy p").textContent=p.sub;n.querySelector(".product-copy strong").textContent=money(p.price);n.querySelector(".product-image").onclick=()=>openProduct(p);n.querySelector(".quick-add").onclick=()=>add(p);grid.appendChild(n)})}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter,document.querySelector("#inlineSearch").value)});
document.querySelector("#inlineSearch").oninput=e=>render(document.querySelector(".filter.active").dataset.filter,e.target.value);
const scrim=document.querySelector("#scrim"),drawer=document.querySelector("#cart");
function openCart(){drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");scrim.hidden=false}function closeCart(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");if(!panel.classList.contains("open"))scrim.hidden=true}
document.querySelector("#bagBtn").onclick=openCart;document.querySelector("#closeCart").onclick=closeCart;
function add(p){cart.set(p.id,(cart.get(p.id)||0)+1);updateCart();closeProduct();openCart()}
function updateCart(){let count=0,total=0,w=document.querySelector("#cartItems");w.innerHTML="";cart.forEach((q,id)=>{let p=products.find(x=>x.id===id);count+=q;total+=p.price*q;let r=document.createElement("div");r.className="cart-item";r.innerHTML=`<div class="cart-thumb" style="background:${p.bg}"></div><div><p><strong>${p.name}</strong></p><p>${q} × ${money(p.price)}</p></div><button class="cart-remove" aria-label="Remove ${p.name}">×</button>`;r.querySelector("button").onclick=()=>{cart.delete(id);updateCart()};w.appendChild(r)});if(!count)w.innerHTML="<p>Your bag is empty.</p>";document.querySelector("#bagCount").textContent=count;document.querySelector("#cartTotal").textContent=money(total);document.querySelector("#shipAmount").textContent=`${money(total)} / $75`;document.querySelector("#shipBar").style.width=Math.min(100,total/75*100)+"%";document.querySelector("#shipMessage").textContent=total>=75?"Free shipping unlocked":"Add "+money(75-total)+" for free shipping"}
const panel=document.querySelector("#productPanel");
function openProduct(p){active=p;document.querySelector("#panelVisual").innerHTML=art(p);document.querySelector("#panelBadge").textContent=p.badge;document.querySelector("#panelName").textContent=p.name;document.querySelector("#panelSub").textContent=p.sub;document.querySelector("#panelPrice").textContent=money(p.price);panel.classList.add("open");panel.setAttribute("aria-hidden","false");scrim.hidden=false}
function closeProduct(){panel.classList.remove("open");panel.setAttribute("aria-hidden","true");if(!drawer.classList.contains("open"))scrim.hidden=true}
document.querySelector("#closePanel").onclick=closeProduct;document.querySelector("#panelAdd").onclick=()=>active&&add(active);document.querySelectorAll("#sizeChips button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#sizeChips button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});scrim.onclick=()=>{closeCart();closeProduct()};
const sd=document.querySelector("#searchDialog"),ds=document.querySelector("#dialogSearch"),sr=document.querySelector("#searchResults");document.querySelector("#searchBtn").onclick=()=>{sd.showModal();setTimeout(()=>ds.focus(),50)};document.querySelector("#closeSearch").onclick=()=>sd.close();function search(){let q=ds.value.toLowerCase(),hits=products.filter(p=>`${p.name} ${p.sub}`.toLowerCase().includes(q));sr.innerHTML=hits.map(p=>`<button class="search-result" data-id="${p.id}"><span>${p.name}</span><strong>${money(p.price)}</strong></button>`).join("")||"<p>No matches.</p>";sr.querySelectorAll("button").forEach(b=>b.onclick=()=>{sd.close();openProduct(products.find(p=>p.id===b.dataset.id))})}ds.oninput=search;search();
const mb=document.querySelector("#menuBtn"),mm=document.querySelector("#mobileMenu");mb.onclick=()=>{let o=mb.getAttribute("aria-expanded")==="true";mb.setAttribute("aria-expanded",String(!o));mm.hidden=o};mm.querySelectorAll("a").forEach(a=>a.onclick=()=>{mm.hidden=true;mb.setAttribute("aria-expanded","false")});
document.querySelector("#checkoutBtn").onclick=()=>alert("Connect this to Printify, Printful, Shopify, Stripe, or your own checkout.");
document.querySelector("#newsletterForm").onsubmit=e=>{e.preventDefault();document.querySelector("#newsletterStatus").textContent="You’re on the list. Connect your email provider before launch.";e.target.reset()};
render();updateCart();